name: save-logs
description: "Save debug logs"

inputs:
  suffix:
    description: 'Suffix to append to the debug log'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/zarf-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: debug-log${{ inputs.suffix }}
        path: /tmp/zarf-*.log
