name: Test Site
on:
  pull_request:
  merge_group:

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: site-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3

      - name: npm ci
        run: npm ci

      - name: run site build
        run: npm run build

      - name: check links
        run: npm run link-check
